#!/usr/bin/env python

import sys
import os

options = sys.argv[1:]

def add_file(options):
	zip_name =''

	if (len(options) >= 1) and (options[0] == "-name"):
		if(len(options) <= 2):
			usage()
		options.pop(0);
		zip_name = options.pop(0)

	print(os.getcwd())

def del_file(options): pass
def list_files(options): pass

def usage():
	print ("Usage: share " + "|".join(valid_actions) + " [-name name] files")
	sys.exit()

valid_actions = {
	'add': add_file, 
	'del': del_file, 
	'list': list_files
}

if not len(options):
	usage()


cmd = options.pop(0)

if (cmd not in valid_actions) or (len(options) < 1):
	usage()

valid_actions[cmd](options)

